kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-pvc
  namespace: k6-operator-system
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
